[build]
    publish = "build"
    command = "npm run build"

[[redirects]]
    from = "https://domineering.netlify.app/*"
    to = "https://domineering.pgdp.de/:splat"
    status = 301
    force = true
